<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \TUTJunior\CourseType\Block\Customer\Wishlist\Item\Column\CourseLabel $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();

if($product->getTypeId() === 'course_type'):
$doc = $block->getCourseDocument($product->getDocument());
?>
<div>
    <img src="<?= $doc->getIcon() ?>">
    <span><?= $doc->getFileLabel() ?></span>
</div>
<?php endif; ?>
