<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \TUTJunior\CancelOrder\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                        </a>
                        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?= /* @noEscape */
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                            </a>
                        <?php endif ?>
                        <?php if($_order->getStatus() === 'pending'):?>
                        <a href="#" class="action cancel" data-cancel-order-id="<?= $block->escapeHtml($_order->getEntityId()) ?>" data-email="<?= $block->escapeHtml($_order->getCustomerEmail()) ?>">
                            <span><?= $block->escapeHtml(__('Cancel Order')) ?></span>
                        </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
<?php if(!empty($block->getReasonsOrderCancel())): ?>
<div id="cancel-order-form" style="display: none">
    <form action="<?= $block->escapeUrl($block->getUrl('cancel/order/index')) ?>"
          id="comment-cancel-order-form" method="post">
        <div>
            <input type="hidden" id="cancel-order-id" name="cancel-order-id" value="">
            <input type="hidden" id="customer-email-order" name="customer-email-order" value="">
        </div>
        <div>
            <label>Chose reason for order cancellation</label>
            <select name="reason" class="reason">
                <?php foreach($this->helper('Magento\Framework\Json\Helper\Data')->jsonDecode($block->getReasonsOrderCancel()) as $reason):?>
                    <option value="<?= $reason['reason'] ?>">
                        <?= $reason['reason'] ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
        <br>
        <div>
            <label>Leave a Comment</label>
            <textarea name="comment" class="comment"></textarea>
        </div>
        <input name="form_key" type="hidden" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>" />
        <div class="actions">
            <button type="submit">Submit</button>
        </div>
    </form>
</div>
<?php endif; ?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            $('.cancel').click(function (){
                $('cancel-order-form').css('display','block');
                var cancelOrderId = $(this).data('cancel-order-id');
                var email = $(this).data('email');
                $('#cancel-order-id').val(cancelOrderId);
                $('#customer-email-order').val(email);
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Cancel Order Popup',
                    buttons: [{
                        text: $.mage.__('Close'),
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, $('#cancel-order-form'));

                $('#cancel-order-form').modal('openModal');
            })
        }
    );
</script>
